// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"database/sql"
)

type Message struct {
	ID           int64
	Sender       string
	Recipient    string
	CipherSymKey []byte
	Ciphertext   []byte
	SentAt       sql.NullTime
	DeliveredAt  sql.NullTime
	ReadAt       sql.NullTime
}

type SchemaMigrations struct {
	Version string
}

type User struct {
	Name      string
	PublicKey []byte
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
