// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlcgen

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, name, public_key, created_at, updated_at FROM users WHERE name = $1
`

func (q *Queries) GetUser(ctx context.Context, name string) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (name, public_key) 
VALUES ($1, $2)
ON CONFLICT(name) DO NOTHING
RETURNING id, name, public_key, created_at, updated_at
`

type InsertUserParams struct {
	Name      string
	PublicKey []byte
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Name, arg.PublicKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, public_key, created_at, updated_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
