// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"database/sql"
)

type Conversation struct {
	ID               int64
	LocalUserName    string
	RemoteUserName   string
	LastSymmetricKey []byte
}

type LocalUser struct {
	Name       string
	PrivateKey []byte
}

type Message struct {
	ID             int64
	ConversationID int64
	Sender         string
	Receiver       string
	Content        []byte
	SentAt         sql.NullTime
	DeliveredAt    sql.NullTime
	ReadAt         sql.NullTime
}

type PublicUser struct {
	Name      string
	PublicKey []byte
}

type SchemaMigrations struct {
	Version string
}
